---
title: HW 16
header-includes:
  - \usepackage{bbm}
output:
  pdf_document
---



#### Problem 1 (11.6)

Suppose Guy approaches you (unless you are Guy, in which case suppose you are talking to yourself) with the following argument: "I looked at the measurements for both locations and I calculated the corresponding averages. Why would I need to test whether or not the means are equal when I can already tell this by comparing the averages?" 

Channeling your inner statistician, how would you respond to Guy's question? 
 


\pagebreak

#### Problem 2 (11.18)

Two independent samples are to be compared to see if there is a difference in the population means. (You may assume that the observations in the two samples are normally distributed with the same variance.) If a total of $m$ subjects are available for the experiment, how should this total be allocated between the two samples in order to provide the shortest confidence interval for $\mu_{X} - \mu_{Y}$? 



\pagebreak

#### Problem 3 (11.18)

Two independent samples are to be compared to see if there is a difference in the population means. (You may assume that the observations in the two samples are normally distributed with the same variance.) If a total of $m$ subjects are available for the experiment, how should this total be allocated between the two samples in order to make the test of $H_0: \mu_{X} = \mu_{Y}$ as powerful as possible? 





