---
title: HW 19
header-includes:
  - \usepackage{bbm}
output:
  pdf_document
---

For problems 1-3 consider the following table which gives the measurements on chlorpheniramine maleate tablets from a particular manufacturer (as in Figure 12.1 of your textbook). This data represents the reports from seven different labs that analyzed $10$ different portions of a composite (each) whose weight was equivalent to that of one chlorpheniramine maleate tablet. The composites being measured were prepared beforehand by grinding and mixing together tablets that had nominal dosage levels of $4$mg chlorpheniramine maleate. 

The purpose of the study is to evaluate the use of a semiautomated method for measuring the amount of hlorpheniramine maleate in tablets. Your boss wants you (the data scientist) to analyze the data to see if there could be some systematic differences in the measurements among the labs. Your task is to determine if the data indicates that any differences in the means of the measurements from the various labs are signals of a systematic difference or if they might as well be due to chance.

```{r}
#library("tidyverse")
#mydata <- read.csv2("", header=T)
```

#### Problem 1 (12.20)

List one pro and one con about the statistical decision to use a graphical technique to answer this research question.



\pagebreak

#### Problem 2 (12.20)

List one pro and one con about the statistical decision to use a formal F-test to answer this research question.



\pagebreak

#### Problem 3 

Make a decision to use either a graphical technique or an F-test to address this research question and report the results of your analysis. (Make sure you include any relevant graphs or R output.)








