---
title: HW 3
header-includes:
  - \usepackage{bbm}
output:
  pdf_document
---



#### Problem 1 (4.65)

A *random sum* is of the type $T = \sum_{i=1}^{N}X_i$ where $N$ is a RV with a finite expectation and the $X_i$ are RVs that are independent of $N$ and have a common mean $E(X)=\mu$. Consider the random sum where $N$ is the number of jobs in a queue for maintenance repairs to a dorm and $X_i$ is the service time required for the $i$th job in the queue. Thus $T = \sum_{i=1}^{N}X_i$ is the time required to serve all the jobs in the queue. According to the Law of Total Expectation, 
$$E(T) = E[E(T\mid N)].$$
Since $E(T \mid N=n) = nE(X)$, $E(T \mid N) = NE(X)$ and thus 
$$E(T) = E[NE(X)] = E(N)E(X).$$ 
How has the assumption that $N$ and each $X_i$ are independent been used here? 



\pagebreak

#### Problem 2 (Ch 3) 

Suppose $X_1, \dots, X_n$ are IID $Poisson(\lambda)$ RVs. Find the exact distribution of $S_n = \sum_{i=1}^{n}X_i$. 
 
 
 
 

\pagebreak

#### Problem 3 (5.11)

As in the previous problem, suppose $X_1, \dots, X_n$ are IID $Poisson(\lambda)$ RVs and $S_n = \sum_{i=1}^{n}X_i$. What is the behavior of the distribution of $S_n$ as $n \rightarrow \infty$? Does the CLT apply? Why/why not? 



