---
title: Possible questions
author: Your name here!
output:
  pdf_document  
## You can change the line above to say "pdf_document" instead as long as you 1) have LateX installed on your computer or 2) you are using Swarthmore's RStudio server.  
---

#### Problem X

In the group game called "waterfall", a group of $n$ people sit in a circle and draw cards from a deck. When someone draws an ace they begin drinking their beverage and, in each subsequent person in the circle begins to drink their beverage one-at-a-time. The challenge is that each individual must continue drinking until the person prior to them stops, thus forming a system of connected series. The waterfall ends (i.e. the system fails) if any one of the individuals stops drinking before the person who began drinking prior to them.

Assume Asha, Sarah, Matilda, Amy, and Koji are playing this game and that the amount of time each person can drink non-stop ($X_i$) are independent with density
$$ f(x) = \lambda e^{-\lambda x}\mathbb{I}\{x \geq 0\}.$$
Let $V=X_{(1)}$ be the random variable representing the lifetime of the waterfall for this group. 

(a) What is the distribution of $V$? 

(b) What is the likelihood of $\tau = 1/\lambda$? 

(c) What is the MLE of $\tau$? 


## Chapter 8 


#### Problem 1 (8.31)

Anne spins a (fair) coin three times and observes no heads. She givens the coin to Noha who decides to spin the coin until a heads occurs. Noha spins the coin a total of four times. Let $\theta$ be the probability the coin comes up heads. 

(a) What is the likelihood of $\theta$? 

(b) What is the MLE for $\theta$? 


\pagebreak

#### Problem 2 (8.21)

Suppose that $X_1, \dots, X_n$ are IID with density $f(x) = e^{-(x-\theta)}\mathbbm{I}\{ x \geq \theta\}$.

(a) Find the method of moments estimate of $\theta$. 

(b) Draw a sketch of the likelihood function for observed data $(x_1, x_2, x_3)=(1, 2, -1)$. 



\pagebreak

#### Problem 3 (8.21)

As in the previous problem, suppose that $X_1, \dots, X_n$ are IID with density $f(x) = e^{-(x-\theta)}\mathbbm{I}\{ x \geq \theta\}$. Find the MLE of $\theta$. 



\pagebreak 

#### Problem 4 (8.4)

Suppose $X$ is a discrete RV with mass function
\begin{eqnarray*}
P(X=0) &=& \frac{2}{3}\theta \\
P(X=1) &=& \frac{1}{3}\theta \\
P(X=2) &=& \frac{2}{3}(1-\theta) \\
P(X=3) &=& \frac{1}{3}(1-\theta),
\end{eqnarray*}
where $0 \leq \theta \leq 1$. The following $10$ independent observations were taken from this distribution: $(3, 0, 2, 1, 3, 2, 1, 0, 2, 1)$.

(a) Find the likelihood for $\theta$. 

(b) Assume the prior $\theta \sim Unif[0,1]$ and find the posterior distribution for $\theta$. 




